version: "3.8"

services:
  app:
    platform: "linux/amd64"
    image: ghcr.io/<OWNER>/photo-to-citation:photo-citation
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photo-citation.rule=Host(`730op.synology.me`) && PathPrefix(`/photo-citation`)"
      - "traefik.http.routers.photo-citation.entrypoints=https"
      - "traefik.http.routers.photo-citation.tls=true"
      - "traefik.http.routers.photo-citation.tls.certresolver=myresolver"
      - "traefik.http.services.photo-citation.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.photo-citation-stripprefix.stripprefix.prefixes=/photo-citation"
      - "traefik.http.routers.photo-citation.middlewares=photo-citation-stripprefix"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - web

  watchtower:
    image: containrrr/watchtower
    command: --interval 300 --cleanup --label-enable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  web:
    external: true
