module.exports = [
  {
    name: "caseStore",
    input: "src/lib/caseStore.ts",
    output: "src/generated/zod/caseStore.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "email",
    input: "src/lib/email.ts",
    output: "src/generated/zod/email.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "exif",
    input: "src/lib/exif.ts",
    output: "src/generated/zod/exif.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "geocode",
    input: "src/lib/geocode.ts",
    output: "src/generated/zod/geocode.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "ownershipModules",
    input: "src/lib/ownershipModules.ts",
    output: "src/generated/zod/ownershipModules.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "reportModules",
    input: "src/lib/reportModules.ts",
    output: "src/generated/zod/reportModules.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "vinSources",
    input: "src/lib/vinSources.ts",
    output: "src/generated/zod/vinSources.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "snailMail",
    input: "src/lib/snailMail.ts",
    output: "src/generated/zod/snailMail.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "snailMailProviders",
    input: "src/lib/snailMailProviders.ts",
    output: "src/generated/zod/snailMailProviders.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "citationStatusModules",
    input: "src/lib/citationStatusModules.ts",
    output: "src/generated/zod/citationStatusModules.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
  {
    name: "openai",
    input: "src/lib/openai.ts",
    output: "src/generated/zod/openai.ts",
    skipValidation: true,
    jsDoc: "extended",
  },
];
