import { authOptions } from "@/lib/authOptions";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import AuthProvider from "./auth-provider";
import NavBar from "./components/NavBar";
import NotificationProvider from "./components/NotificationProvider";
import QueryProvider from "./query-provider";
import "./globals.css";

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  height: "device-height",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="antialiased">
        <QueryProvider>
          <NotificationProvider>
            <AuthProvider session={session}>
              <NavBar />
              {children}
            </AuthProvider>
          </NotificationProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
