import { authOptions } from "@/lib/authOptions";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { cookies } from "next/headers";
import AuthProvider from "./auth-provider";
import NavBar from "./components/NavBar";
import NotificationProvider from "./components/NotificationProvider";
import I18nProvider from "./i18n-provider";
import QueryProvider from "./query-provider";
import "./globals.css";

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const storedLang = cookies().get("language")?.value ?? "en";
  return (
    <html lang={storedLang}>
      <body className="antialiased">
        <QueryProvider>
          <I18nProvider lang={storedLang}>
            <NotificationProvider>
              <AuthProvider session={session}>
                <NavBar />
                {children}
              </AuthProvider>
            </NotificationProvider>
          </I18nProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
