import { authOptions } from "@/lib/authOptions";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { cookies, headers } from "next/headers";
import AuthProvider from "./auth-provider";
import NavBar from "./components/NavBar";
import NotificationProvider from "./components/NotificationProvider";
import I18nProvider from "./i18n-provider";
import QueryProvider from "./query-provider";
import "./globals.css";

export const runtime = "nodejs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const cookieStore = cookies();
  // Prefer the language cookie but fall back to Accept-Language
  let storedLang = cookieStore.get("language")?.value;
  if (!storedLang) {
    const accept = headers().get("accept-language") ?? "";
    // Parse the first supported locale from the Accept-Language header
    const supported = ["en", "es", "fr"];
    for (const part of accept.split(",")) {
      const code = part.split(";")[0].trim().toLowerCase().split("-")[0];
      if (supported.includes(code)) {
        storedLang = code;
        break;
      }
    }
    storedLang = storedLang ?? "en";
    // The client persists this value in a cookie on first render
  }
  return (
    <html lang={storedLang}>
      <body className="antialiased">
        <QueryProvider>
          <I18nProvider lang={storedLang}>
            <NotificationProvider>
              <AuthProvider session={session}>
                <NavBar />
                {children}
              </AuthProvider>
            </NotificationProvider>
          </I18nProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
