name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs:
  lint_typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - name: Upload node modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules

  test:
    runs-on: ubuntu-latest
    needs: lint_typecheck
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: .
      - run: npm test

  e2e:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: .
      - run: npm run e2e

  storybook:
    runs-on: ubuntu-latest
    needs: e2e
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: .
      - run: npm run build-storybook
      - name: Deploy Storybook to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
          destination_dir: storybook
